### ISSUE TITLE
make epubcheck-adapter work with pipeline v1.10

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline-scripts-utils#56]

**Comment by rdeltour** [comment]
Depends on an unreleased version of EpubCheck, so let's defer to v1.10 (maybe v1.9.1 if we do it).

**Comment by josteinaj** [comment]
@rdeltour: I see there's been a couple of epubcheck alpha releases since last I checked (I haven't checked in a while). If these work with the epubcheck-adapter (I haven't tested yet), do you think it would be ok to bundle epubcheck with DP2?

**Comment by rdeltour** [comment]
yes, it w/b good. But I'd suggest waiting a little longer; some pending EpubChcek commits will change some libs, so better synchronize with them for the adapter.

**Comment by josteinaj** [comment]
Ok, np.
